name: Aseprite Windows Automated Build and Release

on:
  workflow_dispatch:

jobs:
  setup-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          repository: "aseprite/aseprite"

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Visual Studio Components
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 18362

      - name: Setup Ninja Build System
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: "1.10.0"

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Download and Setup Skia
        run: |
          New-Item -ItemType Directory -Force -Path "C:\deps\skia"
          Invoke-WebRequest -Uri "https://github.com/aseprite/skia/releases/latest/download/Skia-Windows-Release-x64.zip" -OutFile "Skia-Windows-Release-x64.zip"
          Expand-Archive "Skia-Windows-Release-x64.zip" -DestinationPath "C:\deps\skia"

      - name: Compile Aseprite
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G "Ninja" ..
          ninja aseprite

      - name: Upload Aseprite Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aseprite-windows-x64
          path: build/bin/aseprite.exe

      - name: Create Release
        id: create_release
        uses: joutvhu/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            Automatically generated Aseprite release for Windows.

            Changes in this Release:
            - First Change
            - Second Change
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/bin/aseprite.exe
          asset_name: aseprite-windows-x64.exe
          asset_content_type: application/octet-stream
